### ISSUE TITLE
Put rename_nifti.py into I-SPY and QIN_BMMR projects

### ISSUE THREAD

**Issue by njahani** [hsieh42/exit_process#34]
It's missing in the project directories. It's still in Michael's home directory.

**Comment by njahani** [comment]
please also put the code in dicom_manipulation repo.

**Comment by hsieh42** [comment]
[dicom2nifti](https://github.com/hsieh42/dicom2nifti) repo created. Instead of putting it in `dicom_manipulation` repo, having it in `dicom2nifti` is more natural as `rename_nifti.py` has been part of the `dicom2nifti` functionality. [rename_nifti.py](https://github.com/hsieh42/dicom2nifti/blob/master/dicom2nifti/rename_nifti.py) can be found and deployed into the project directory along with the `dicom2nifti` package.

git repo cloned in `/cbica/projects/QIN_BMMR/Scripts/dicom2nifti-git` and `/cbica/projects/I-SPY/Scripts/dicom2nifti-git`
