### ISSUE TITLE
Document lung related codes and create a github repo

### ISSUE THREAD

**Issue by hsieh42** [hsieh42/exit_process#7]
- Lung segmentation in [libra_lung.py](https://sbia-svn/projects/BreastCAD/branches/pyLIBRA_lung_0.1/libra/libra_lung.py) and [segmentation.py](https://sbia-svn/projects/BreastCAD/branches/pyLIBRA_lung_0.1/libra/segmentation.py)
- Texture feature clustering with k-mean and modeling with logit in ```/cbica/projects/ILD_Lung/Scripts/feature_clustering.py``` 
- DICOM segmentation object conversion, used for SIEMENS syngo.via output: ```/cbica/projects/ILD_Lung/Scripts/convert_dicom_seg.py```
- Submission scripts: ```/cbica/projects/ILD_Lung/Scripts/sendTexturePipeline_Lung3D_cooc_fixed.sh``` and ```/cbica/projects/ILD_Lung/Scripts/sendTexturePipeline_Lung3D_cooc_fixed_mask_fixed.sh```. The latter addressed the linearly interpolated resampled masks due to unknown reason. However, texture and clustering results are created with the former.

**Comment by hsieh42** [comment]
@bhaghighi could you please take a look at the segmentation codes? Would love to hear some feedback. Let's talk about it together.

**Comment by bhaghighi** [comment]
@hsieh42 Thanks Micheal. I am reading it and will talk about it this week.

**Comment by bhaghighi** [comment]
@hsieh42 I am trying to reproduce the results. It would be great if we could go through one subjects together? thanks

**Comment by hsieh42** [comment]
Data is in `/cbica/projects/ILD_Lung/Pipelines/renamedNifti` which is a symbolic link to `/cbica/projects/ILD_Lung/Data/renamedNifti_linear/`.

Try the case 7: `/cbica/projects/ILD_Lung/Pipelines/renamedNifti/7-20090512` first. Runtime is quick so feel free to run them all.

**Comment by hsieh42** [comment]
pyLIBRA_lung branch created: <url>https://github.com/CBICA/pyLIBRA/tree/pyLIBRA_lung</url>. Not tested yet.

**Comment by hsieh42** [comment]
I have submitted an [elog ](https://cbica-infr-velog.uphs.upenn.edu/elog/CBICA+Cluster/14676)to request a private repo in CBICA for all ILD related codes and scripts.

**Comment by bhaghighi** [comment]
@hsieh42 
I activated the virtual environment with _edm_ and then run python _setup.py install_ 
after running 
_>>> from libra import libra_lung_   i am getting this:
**/cbica/home/haghighb/.local/share/canopy/edm/envs/venv3/lib/python2.7/site-packages/scikit_learn-0.18.1-py2.7-linux-x86_64.egg/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)**

**Comment by bhaghighi** [comment]
getting this :) do I need to use sendSegmentLung_pylibra.sh instead of segment_lung.py? it can not be run locally? 
(venv3)[haghighb@crete Scripts]$ python segment_lung.py -i /cbica/projects/ILD_Lung/Pipelines/renamedNifti/7-20090512 -o /cbica/projects/ILD_Lung/Pipelines/LungSegmentation_21/7-20090512_Seg_BH
**Command segment_lung.py
Arguments Namespace(bins=100, inputfile='/cbica/projects/ILD_Lung/Pipelines/renamedNifti/7-20090512', lower=None, output='/cbica/projects/ILD_Lung/Pipelines/LungSegmentation_21/7-20090512_Seg_BH', upper=None)
Executing on crete.uphs.upenn.edu
Executing at 2018-09-27 Thu 14:09:41
Executing in /cbica/projects/ILD_Lung/Scripts
/cbica/home/haghighb/.local/share/canopy/edm/envs/venv3/lib/python2.7/site-packages/scikit_learn-0.18.1-py2.7-linux-x86_64.egg/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
>> Segmenting...
Traceback (most recent call last):
  File "segment_lung.py", line 253, in <module>
    sys.exit(main())
  File "segment_lung.py", line 215, in main
    mask, kmeans, cutoff_low, cutoff_high = segment_lung_kmean(img, lower = args.lower, upper = args.upper, bins = args.bins)
UnboundLocalError: local variable 'img' referenced before assignment**

**Comment by bhaghighi** [comment]
the previous fixed but this time:
**python segment_lung.py -i /cbica/projects/ILD_Lung/Data/Nifti/10-20091117/10-20091117_EXPIRATION__1.0__B41f-9.nii.gz -o /cbica/projects/ILD_Lung/Pipelines/LungSegmentation_21/7-20090512_Seg_BH
Command segment_lung.py**

_File "/cbica/home/haghighb/.local/share/canopy/edm/envs/venv3/lib/python2.7/site-packages/matplotlib-2.2.3-py2.7-linux-x86_64.egg/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/cbica/home/haghighb/.local/share/canopy/edm/envs/venv3/lib/python2.7/site-packages/matplotlib-2.2.3-py2.7-linux-x86_64.egg/matplotlib/axes/_axes.py", line 5501, in imshow
    im.set_data(X)
  File "/cbica/home/haghighb/.local/share/canopy/edm/envs/venv3/lib/python2.7/site-packages/matplotlib-2.2.3-py2.7-linux-x86_64.egg/matplotlib/image.py", line 654, in set_data
    raise TypeError("Invalid dimensions for image data")
TypeError: Invalid dimensions for image data_

**Comment by hsieh42** [comment]
Do not use `segment_lung.py` as it is a prototype code for 2D slices only. 

Please open a new issue in https://github.com/CBICA/pyLIBRA should there be any segmentation related bugs and issues.
